micronaut:
  security:
    ldap:
      default: 
        context:
          server: 'ldaps://db.debian.org'  
          managerDn: 'cn=read-only-admin,dc=debian,dc=org'  
          managerPassword: 'password'  
        search:
          base: "dc=debian,dc=org"  
        groups:
          enabled: true  
          base: "dc=debian,dc=org" 
  application:
    name: groveBackend
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}

datasources:
  default:
    driverClassName: org.postgres.Driver
    db-type: postgres
    dialect: POSTGRES
    schema-generate: CREATE_DROP
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
