micronaut:
  application:
    name: groveBackend
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: MYSQL
      url: r2dbc:mysql://localhost:3306/db
      username: grove
      password: 'grow_your_grove'
datasources:
  default:
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3

flyway:
  datasources:
    default:
      enabled: true
