micronaut:
  security:
    ldap:
      default: 
        context:
          server: 'ldaps://db.debian.org'  
          managerDn: 'cn=read-only-admin,dc=debian,dc=org'  
          managerPassword: 'password'  
        search:
          base: "dc=debian,dc=org"  
        groups:
          enabled: true  
          base: "dc=debian,dc=org" 
  application:
    name: groveBackend
  security:
    authentication: session
    redirect:
      login-success: /
      login-fail: /login/failedAuth
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: MYSQL
      url: r2dbc:mysql://localhost:3306/db
      username: grove
      password: 'grow_your_grove'
datasources:
  default:
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3

flyway:
  datasources:
    default:
      enabled: true
